#!/bin/bash
{
export SXHKD_SHELL='/usr/bin/sh'

bspc config border_width    2
bspc config window_gap      9

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true
bspc config remove_unplugged_monitors  true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor DP-2 -d 6 7 8 9 0

fg_color="#cc7a00"
bg_color="#4d2600"

bspc config focused_border_color  "$fg_color"
bspc config presel_feedback_color "$fg_color"
bspc config normal_border_color   "$bg_color"
bspc config active_border_color   "$bg_color"

bspc rule -a Orage state=floating follow=on
#bspc rule -a Matplotlib state=floating follow=on

xsetroot -cursor_name left_ptr
xset s 1800 # blank screen after N seconds of inactivity
xset +dpms # enable DPMS
xset dpms 1800 3600 0 # trigger display {standby, suspend, off} after N seconds of inactivity

[ -f ~/.config/bspwm/startup_apps.sh ] && ~/.config/bspwm/startup_apps.sh

} &> /tmp/bspwmrc.log
